### ISSUE TITLE
Fullscreen button missing

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSVimeo#17]
OSVimeo outputs the iframe tag without the required fullscreen attributes:
            webkitallowfullscreen mozallowfullscreen allowfullscreen

To fix this, change the $attribs array (in osvimeo.php) to:
            $attribs = array(
                'width'                 => $width,
                'height'                => $height,
                'src'                   => '//player.vimeo.com/video/' . $vCode,
                'frameborder'           => '0',
                'webkitallowfullscreen' => 'webkitallowfullscreen',
                'mozallowfullscreen'    => 'mozallowfullscreen',
                'allowfullscreen'       => 'allowfullscreen',
            );

Or add them to the <iframe> tag directly:
            $output .= '<iframe ' . JArrayHelper::toString($attribs) . ' webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';

**Comment by nicksavov** [comment]
Related:
https://github.com/OSTraining/OSVimeo/issues/16#issuecomment-183372088
